### ISSUE TITLE
App crashes with either exception

### ISSUE THREAD

**Issue by Bluefissure** [LeonBlade/BurningDownTheHouse#5]
Either exception in [local offset](https://github.com/LeonBlade/BurningDownTheHouse/blob/master/BurningDownTheHouse/Services/OffsetsService.cs#L37) or [remote offset](https://github.com/LeonBlade/BurningDownTheHouse/blob/master/BurningDownTheHouse/Services/OffsetsService.cs#L52) will crash the application from starting.

I tried to change the severity to `Log.Severity.Warning`, the weird thing is the app crashes after finishing starting the `SelectedItemService`.

You can reproduce this bug by changing the [URL of offset](https://github.com/LeonBlade/BurningDownTheHouse/blob/master/BurningDownTheHouse/Services/OffsetsService.cs#L15) to an arbitrary 404 page and see whether the app starts normally.

**Comment by LeonBlade** [comment]
I'm already rewriting this code anyway because the way it's handled currently is bad, plus I'm using the new serialization stuff.
